# Generated by Django 4.0.2 on 2022-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classes',
            new_name='parent_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('BCH', 'Bachelor'), ('MST', 'Master'), ('PHD', 'Doctorate')], max_length=3),
        ),
    ]
