# Generated by Django 4.0.2 on 2022-10-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_class_teacher_subject_student_attendanceform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('5', 'Saturday'), ('6', 'Sunday'), ('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TimeTableObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('daily_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailytimetable')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
            ],
        ),
        migrations.AddField(
            model_name='dailytimetable',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timetable'),
        ),
    ]
