# Generated by Django 4.1.2 on 2022-11-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_student_profile_pic_teacher_profile_pic"),
        ("subject_class", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectClassTeacherInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject_class.classes",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject_class.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("5", "Saturday"),
                            ("6", "Sunday"),
                            ("0", "Monday"),
                            ("1", "Tuesday"),
                            ("2", "Wednesday"),
                            ("3", "Thursday"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "cridet",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                        max_length=1,
                    ),
                ),
                (
                    "subject_class_teacher_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject_class.subjectclassteacherinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isPresent", models.BooleanField()),
                ("date", models.DateField()),
                (
                    "cridet",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                        max_length=1,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
                (
                    "subject_class_teacher_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject_class.subjectclassteacherinfo",
                    ),
                ),
            ],
        ),
    ]
