# Generated by Django 4.1.2 on 2022-10-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject_class", "0002_subjectclassteacherinfo_timetable_attendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timetable",
            old_name="Day_of_week",
            new_name="day_of_week",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="cridet",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="cridet",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")], max_length=1
            ),
        ),
    ]
